### ISSUE TITLE
Address:  2-of-3 Multisig Address Generation

### ISSUE THREAD

**Issue by enigbe** [enigbe/bitcoin-cosign#7]
- Generate service xpub
- Generate children xpubs from user-provided xpubs
- Create P2WSH address

**Comment by tvpeter** [comment]
I think we might need to save the service-generated master private key for signing transactions. It seems we omitted it in our initial flow. What do you think @enigbe ?

**Comment by tvpeter** [comment]
Infact, with the way we are generating service pub keys, we need to rethink our address table so that we'll have enough information for signing transactions

**Comment by enigbe** [comment]
> I think we might need to save the service-generated master private key for signing transactions. It seems we omitted it in our initial flow. What do you think @enigbe ?

Do you think it might be better to consider a wallet for the service? In that way we can create one xpriv and generate all the xpubs needed from it.

**Comment by tvpeter** [comment]
> Do you think it might be better to consider a wallet for the service? In that way we can create one xpriv and generate all the xpubs needed from it.

Yes, this will be more efficient as the service can be able to generate addresses and sign transactions with the same pub/priv keys.
